# Generated by Django 3.0 on 2019-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='squirrel',
            fields=[
                ('x', models.DecimalField(blank=True, decimal_places=12, default=None, max_digits=1007)),
                ('y', models.DecimalField(blank=True, decimal_places=12, default=None, max_digits=1006)),
                ('unique_squirrel_id', models.CharField(blank=True, default=None, max_length=14, primary_key=True, serialize=False)),
                ('hectare', models.CharField(blank=True, default=None, max_length=3)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('AM', 'PM')], default='AM', max_length=2)),
                ('date', models.CharField(blank=True, default=0, max_length=20)),
                ('hectare_squirrel_number', models.IntegerField(blank=True, default=0)),
                ('age', models.CharField(blank=True, default=None, max_length=8)),
                ('primary_fur_color', models.CharField(blank=True, default=None, max_length=8)),
                ('highlight_fur_color', models.CharField(blank=True, default=None, max_length=100)),
                ('combination_of_primary_and_highlight_color', models.CharField(blank=True, default=None, max_length=100)),
                ('color_notes', models.CharField(blank=True, default=None, max_length=100)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default='Ground Plane', max_length=100)),
                ('above_ground_sighter_measurement', models.CharField(blank=True, default=None, max_length=10)),
                ('specific_location', models.CharField(blank=True, default=None, max_length=100)),
                ('running', models.BooleanField(blank=True, default=None)),
                ('chasing', models.BooleanField(blank=True, default=None)),
                ('climbing', models.BooleanField(blank=True, default=None)),
                ('eating', models.BooleanField(blank=True, default=None)),
                ('foraging', models.BooleanField(blank=True, default=None)),
                ('other_activities', models.CharField(blank=True, default=None, max_length=100)),
                ('kuks', models.BooleanField(blank=True, default=None)),
                ('quaas', models.BooleanField(blank=True, default=None)),
                ('moans', models.BooleanField(blank=True, default=None)),
                ('tail_flags', models.BooleanField(blank=True, default=None)),
                ('tail_twitches', models.BooleanField(blank=True, default=None)),
                ('approaches', models.BooleanField(blank=True, default=None)),
                ('indifferent', models.BooleanField(blank=True, default=None)),
                ('runs_from', models.BooleanField(blank=True, default=None)),
                ('other_interactions', models.CharField(blank=True, default=None, max_length=100)),
                ('lat_long', models.CharField(blank=True, default=None, max_length=100)),
                ('zip_codes', models.CharField(blank=True, default=None, max_length=100)),
                ('community_districts', models.IntegerField(blank=True, default=0)),
                ('borough_boundaries', models.IntegerField(blank=True, default=0)),
                ('city_coucil_districts', models.IntegerField(blank=True, default=0)),
                ('police_precincts', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
